#! /bin/sh

# PROVIDE: websocket_server
# REQUIRE: netwait

. /etc/rc.subr

name="websocket_server"
rcvar=${name}_enable
pidfile="/var/run/${name}.pid"

command="/usr/home/ec2-user/websocket_server/server.js"
command_args="&"

load_rc_config $name
: ${websocket_server_enable:="NO"}

export websocket_server_pidfile="${pidfile}"
export websocket_server_port
export websocket_server_privkey
export websocket_server_fullchain

run_rc_command "$1"
