#! /bin/sh

# PROVIDE: websocket_server
# REQUIRE: netwait

. /etc/rc.subr

name="websocket_server"
rcvar=${name}_enable
pidfile="/var/run/${name}.pid"

command="/usr/sbin/daemon /usr/local/bin/websocket_server"
command_args="-P ${pidfile} -o /var/log/${name}"

load_rc_config $name
: ${websocket_server_enable:="NO"}

export websocket_server_port
export websocket_server_privkey
export websocket_server_fullchain

run_rc_command "$1"
